added a .env file

diff --git a/.github/workflows/continuous-integration-pipeline.yml b/.github/workflows/continuous-integration-pipeline.yml
--- a/.github/workflows/continuous-integration-pipeline.yml
+++ b/.github/workflows/continuous-integration-pipeline.yml
@@ -147,6 +147,18 @@ jobs:
             fi
             echo "Pulling latest changes..."
             git pull origin main || { echo "Failed to pull latest changes"; exit 1; }
+        
+      - name: Create .env file for docker-compose
+        uses: appleboy/ssh-action@v0.1.8
+        with:
+          host: ${{ vars.EC2_HOST }}
+          username: ${{ vars.EC2_USERNAME }}
+          key: ${{ secrets.EC2_PRIVATE_KEY2 }}
+          script: |
+            cd /home/ubuntu/LucrareLicenta || { echo "Failed to change directory"; exit 1; }
+            echo "SQL_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" > .env
+            echo ".env file created with SQL_PASSWORD"
+
 
       - name: Prune old Docker images
         uses: appleboy/ssh-action@v0.1.8
@@ -166,7 +178,6 @@ jobs:
           key: ${{ secrets.EC2_PRIVATE_KEY2 }}
           script: |
             cd /home/ubuntu/LucrareLicenta || { echo "Failed to change directory"; exit 1; }
-            export SQL_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}"
             echo "Pulling new Docker images..."
             sudo docker-compose pull || { echo "Failed to pull new Docker images"; exit 1; }
 
